version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
    - ./:/var/www
    environment:
    - "DB_PORT=3306"
    - "DB_HOST=bluestarsports-db.c23saagmlxov.us-east-1.rds.amazonaws.com"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
    - app
    ports:
    - 8000:80
  #Mysql Server
  mysql:
    container_name: 'mysql'
    restart: 'always'
    image: 'mysql:5.7'
    volumes:
    - '/data/mysql:/var/lib/mysql'
    environment:
      MYSQL_HOST: 'bluestarsports-db.c23saagmlxov.us-east-1.rds.amazonaws.com'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'RosterBots'
    ports:
    - '3306:3306'
